[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {} 

[project]
name = "xplainable-client"
version = "1.2.8.post2"
authors = [
  { name="xplainable pty ltd", email="contact@xplainable.io" },
]
description = "The client for persisting and deploying models to Xplainable cloud."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10"

classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent"
]

dependencies = [
"numpy>=1.26,<2.0",
"pandas<=1.9.0,>=1.5.2",
"pyperclip",
"Requests",
"scikit_learn",
"setuptools>=65.5.1",
"urllib3",
"xplainable"
]
