[build-system]
requires = [
    "pdm-backend",
    "pdm-build-locked",
]
build-backend = "pdm.backend"

[project]
name = "sphinx-minecraft"
version = "1.0.4"
description = "Add different Minecraft-oriented components to Sphinx."
authors = [
    { name = "theogiraudet", email = "theo.giraudet@altearn.xyz" },
    { name = "Aksiome", email = "maxime.calmon@altearn.xyz" },
]
dependencies = [
    "sphinx",
    "sphinx-treeview==1.1.0",
]
requires-python = ">=3.11"
readme = "README.md"
classifiers = [
    "Intended Audience :: Developers",
    "Framework :: Sphinx :: Extension",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Programming Language :: Python :: 3.11",
]

[project.license]
text = "MPL-2.0"

[project.optional-dependencies]
docs = [
    "myst-parser",
    "furo",
]

[project.urls]
Repository = "https://github.com/Gunivers/Sphinx-Minecraft/tree/main"
Issues = "https://github.com/Gunivers/Sphinx-Minecraft/issues"

[tool]
