[project]
name = "dongzc1025-mcp-demo"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dongzca", email = "dongzca@digitalchina.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.9.4",
]

[project.scripts]
dongzc1025-mcp-demo = "dongzc1025_mcp_demo:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
