[project]
name = "govinfo"
version = "0.3.0"
description = "A wrapper for the Government Publishing Office's GovInfo API"
readme = "README.md"
authors = [
    { name = "William Blackerby", email = "wmblackerby@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.4",
    "pytest>=8.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
