[project]
name = "auth_db_neonix"
version = "0.2.1"
description = "User auth, settings management, and local DB handling with Firebase and SQLite"
authors = [
    { name="NeoNix", email="rittoone@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "firebase_admin>=6.9.0",
    "pydantic>=1.9.0",
    "pandas>=2.0.0",
    "cryptography>=45.0.4",
    "fastapi>=0.115.12",
    "python-dotenv>=1.1.0",
    "Requests>=2.32.4"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "flake8>=5.0",
    "black>=23.0",
    "mypy>=1.5"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

#[tool.setuptools]
#packages = ["auth_db_neonix", "auth_db_neonix.dto", "auth_db_neonix.models", "auth_db_neonix.security"]

[tool.setuptools.packages.find]
where = ["."]
include = ["auth_db_neonix*", "auth_db_neonix.*"]

#[tool.setuptools.package-data]
#auth_db_neonix = ["security/*.json"]

[project.scripts]
authdb-main = "auth_db_neonix.main:main"

