[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "fabric_maverick"
version = "0.1.0.post4"
authors = [
  { name="MAQ Software" },
  { name = "Nisarg Patel", email = "nisargp@maqsoftware.com" },
]
maintainers = [
    { name = "Nisarg Patel", email = "nisargp@maqsoftware.com" },
    { name = "Kunal Sarda", email = "kunals@maqsoftware.com" }
]

description = "A Fabric Package for Semantic/Dataset validation"
readme = "README.md"
requires-python=">=3.10,<3.12"

keywords = ["Fabric", "Microsoft Fabric", "Sempy", "Semantic Model", "Report", "Report Compare"]

classifiers = [
    "Development Status :: 3 - Alpha",
    
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",

    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3 :: Only",
    "Framework :: Jupyter"
]

license = { file = "LICENSE" }

dependencies = [
    "thefuzz",
    "semantic-link-sempy>=0.11.0"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.*"]

[project.optional-dependencies]
test = [
    "pytest>=8.2.1",
]

[[tool.mypy.overrides]]
module = "sempy.*,Microsoft.*,System.*,anytree.*,powerbiclient.*,synapse.ml.services.*,polib.*,jsonpath_ng.*"
ignore_missing_imports = true