# pyproject.toml

[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm[git]>=7.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyqdpx"
authors = [
  { name="PethÅ‘ Gergely", email="petho.gergely@etk.unideb.hu" },
]
description = "A Python module to process Qualitative Data Exchange (QDPX) XML files."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "beautifulsoup4>=4.10.0",
    "lxml>=5.3.0",
    "regex>=2024.11.6"
]
dynamic = ["version"]
license = "MIT"
license-files = ["LICENSE.md"]

[project.urls]
"Homepage" = "https://github.com/DEpt-metagenom/pyqdpx"
"Bug Tracker" = "https://github.com/DEpt-metagenom/pyqdpx/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["pyqdpx"]

[tool.setuptools_scm]
write_to = "pyqdpx/_version.py"
local_scheme = "no-local-version"

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "--strict-markers --import-mode=importlib"
testpaths = ["tests"]
