[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "loom-scope"
version = "0.8"
description = "A Plug-and-Play and Comprehensive evaluation framework specifically for long-context models"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipdb",
    "autopep8",
    "docformatter",
    "scikit-learn",
    "modelscope",
    "rank_bm25",
    "hf_xet",
    "gradio",
    "torch==2.6",
    "loguru",
    "peft",
    "openpyxl",
    "bert_score",
    "nltk",
    "rouge",
    "jieba",
    "rouge_score",
    "fuzzywuzzy",
    "html2text",
    "bs4",
    "seaborn",
    "json_repair",
    "wonderwords",
    "tenacity",
    "scipy",
    "datasets",
    "fraction",
    "pymorphy2",
    "evaluate",
    "rwkv",
    "jsonlines",
]

[project.scripts]
"loom-scope.run" = "scripts.run:main"
"loom-scope.eval" = "scripts.eval:main"

[tool.setuptools.packages.find]
include = ["*"]

[tool.setuptools.package-data]
"*" = ["*.md", "*.png", "*.gif", "*.jpg", "*.jpeg", "*.svg", "*.ico"]

# 启用 include-package-data
[tool.setuptools]
include-package-data = true