[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "devolv"
version = "0.1.6"
description = "Modular DevOps Toolkit with IAM policy validation"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [{ name = "Devolv Dev", email = "devolv.dev@gmail.com" }]
dependencies = ["typer>=0.9", "PyYAML"]

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
devolv = "devolv.cli:app"
