[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "branch-network-hydraulics"
version = "0.1.0"
description = "Hydraulic analysis and optimization for branched water distribution systems"
authors = [
  { name="Your Name", email="you@example.com" }
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
  "pandas",
  "numpy",
  "plotly",
  "scipy",
  "networkx"
]

[project.urls]
"Homepage" = "https://github.com/Relkayam/BNHA"
"Bug Tracker" = "https://github.com/Relkayam/BNHA/issues"
