[project]
name = "justserver"
version = "0.1.44"
description = ""
authors = [
    {name = "Knspar",email = "knspar@proton.me"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "typer (>=0.15.2,<0.16.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "fastapi (>=0.115.12,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "pydantic (>=2.11.2,<3.0.0)",
    "pudb (>=2024.1.3,<2025.0.0)",
    "ipython (>=9.1.0,<10.0.0)",
    "dynaconf (>=3.2.10,<4.0.0)",
    "kubernetes (>=32.0.1,<33.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "justniffer-cli (>=0.2.2,<0.3.0)"
]

[tool.poetry]
packages = [{include = "justserver", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
justserver = "justserver.cli:app"