[tool.poetry]
name = "sag-py-auth-brand"
version = "1.2.3"
description = "Keycloak brand/instance authentication for python projects"
authors = ["Samhammer AG"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
contextvars = "^2.4"
fastapi = { version = ">=0.115.12", extras = ["standard"] }
sag-py-auth = ">=1.2.1"

[tool.poetry.group.dev.dependencies]
build = ">=1.2.2.post1"
coverage = "*"
coverage-lcov = "*"
flake8 = ">=7.2.0"
mock = "*"
mypy = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
types-mock = "*"
toml = "*"
zipp = ">=3.21.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
