[project]
name = "AviListPy"
version = "1.0.6"
authors = [
  { name="Thomas Lee", email="tl165@rice.edu" },
]
maintainers = [
  {name = "Thomas Lee", email = "tl165@rice.edu"}
]
description = "Python implementation of the 2025 AviList Global Avian Checklist."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
license = "CC0-1.0"
license-files = ["LICEN[CS]E*"]
dependencies=["pandas >= 2.3.0",
              "openpyxl >= 3.1.5"
             ]

[build-system]
# Minimum requirements for the build system to execute.
# see PEP518: https://www.python.org/dev/peps/pep-0518/
requires = [
    "setuptools"
    ]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/geothomaslee/AviListPy/"
Issues = "https://github.com/geothomaslee/AviListPy/issues"