[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "extratools-api"
version = "0.1.1"
description = ""
authors = [{ name = "Chuancong Gao", email = "chuanconggao@users.noreply.github.com" }]
requires-python = ">=3.12"
readme = "README.md"
license = "MIT"
dependencies = [
    "extratools-core>=0.1.27",
]

[project.urls]
Repository = "https://github.com/chuanconggao/extratools-api"

[project.optional-dependencies]
fastapi = [
    "fastapi>=0.115.12",
]

[dependency-groups]
dev = [
    "pytest-cov>=6.1.0",
    "mypy>=1.15.0",
    "ipython>=9.2.0",
    "fastapi[standard]>=0.115.12",
]

[tool.coverage.run]
source = [
    "src",
]

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report xml:cov.xml --cov-report html --cov-report term-missing test"
pythonpath = [
    "src",
]
