[project]
name = "tisthemachinelearner"
version = "0.4.1"
description = "Lightweight interface to scikit-learn, with 2 classes"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["scikit-learn", "nnetsauce"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)
include = ["tisthemachinelearner*"]  # package names should match these glob patterns
