[project]
name = "manimgeo"
version = "1.3.1a1"
description = "A library for Geometry constructing and animation generating."
authors = [
    { name = "lifecheckpoint", email = "lifechpt@qq.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.21.0",
    "pydantic>=2.11.7",
]

[project.optional-dependencies]
manim = [
    "manimgl>=1.7.2",
]
janim = [
    "janim>=3.4.0",
    "janim[gui]>=3.4.0",
]
dev = [
    "furo>=2024.8.6",
    "myst-parser>=4.0.1",
    "py-spy>=0.4.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "sphinx>=8.2.3",
    "sphinx-autodoc-typehints>=3.2.0",
]
full = [
    "manimgeo[manim]",
    "manimgeo[janim]",
    "manimgeo[dev]",
]

[project.urls]
Homepage = "https://github.com/LifeCheckpoint/ManimGeo"
