[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "lightning-pose-app"
version = "1.8.1a3"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "wcmatch",
    "tomli",
    "tomli_w",
]

[tool.poetry]
packages = [
    { include = "litpose_app", from = "src" }
]
# We need this to override the .gitignore.
include = ["**/ngdist/**/*"]

