[project]
name = "nber-cli"
version = "0.1.2"
description = "A command-line tool to download NBER papers."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp",
    "aiosqlite",
    "orjson",
    "fake_useragent",
    "aiohttp-retry",
    "certifi"
]

[project.scripts]
nber-cli = "nber_cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
