[tool.poetry]
name = "defectpl"
version = "0.1.5"
description = "A unified package for optical properties of point defects."
authors = ["Shibu Meher <shibumeher@iisc.ac.in>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/Shibu778/defectpl"
repository = "https://github.com/Shibu778/defectpl"
documentation = "https://Shibu778.github.io/defectpl/"
keywords = ["defects", "optical properties", "point defects", "DFT", "VASP", "pymatgen"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6.0.2"
numpy = "^2.1.2"
pymatgen = "2024.10.3"
pdoc3 = "^0.11.1"
click = "^8.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
defectpl = 'defectpl.cli:main'