[project]
name = "langchain-search-django"
version = "0.1.0"
description = "A Django app for integrating LangChain with search capabilities"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.3",
    "langchain==0.3.25",
    "langchain-community==0.3.24",
    "openai==1.85.0",
    "langchain-openai==0.3.21",
    "faker (>=25.0.0,<26.0.0)",
    "pydantic==2.11.5",
]
