[tool.poetry]
name = "digy"
version = "0.1.11"
description = "Do Interactive Git deploY - Deploy Python applications from Git repositories in isolated environments with interactive menu"
authors = ["Tom Sapletta <info@softreck.dev>"]
readme = "README.md"
homepage = "https://github.com/pyfunc/digy"
repository = "https://github.com/pyfunc/digy"
documentation = "https://github.com/pyfunc/digy"
keywords = ["deployment", "git", "python", "interactive", "isolated"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]


[tool.poetry.dependencies]
python = ">=3.9"
requests = "^2.31.0"
gitpython = "^3.1.40"
click = "^8.1.7"
rich = "^13.7.0"
psutil = "^5.9.6"
readchar = "^4.0.4"
virtualenv = "^20.24.6"
docker = "^6.1.3"
pyyaml = "^6.0.1"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
black = "^23.11.0"
flake8 = "^6.1.0"
mypy = "^1.7.1"

[tool.poetry.scripts]
digy = "digy.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"