[tool.poetry]
name = "a79"
version = "0.1.29"
description = "A79 AI Library"
authors = ["A79 AI <dev@a79.ai>"]
packages = [
    {include = "a79", from = "src"},
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/a79ai/a79"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11"
]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 
