[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-streamable-weather-sxw"
version = "0.1.3"
description = "输入心知天气-API-KEY，获取实时天气信息。"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.9.4",
    "requests>=2.32.4",
]

[project.scripts]
mcp-streamable-weather-sxw = "mcp_weather_http_sxw:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]