[project]
name = "boring-semantic-layer"
version = "0.0.3"
description = "A boring semantic layer built with ibis"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ibis-framework>=10.6.0",
    "urllib3>=2.2.3",
]

[project.optional-dependencies]
examples = ["duckdb>=1.3.1"]

[project.scripts]
hello = "boring_semantic_layer:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.6.7",
    "pre-commit>=4.2.0",
    "ipython>=9.3.0",
    "duckdb>=1.3.1",
    "pytest"
]