[project]
name = "balajiwork"
version = "1.1.3"
description = "Balaji's personal utility library"
authors = [
  { name = "Balaji Balagurusami", email = "mail@balaji.work" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["PyPDF2","IfcOpenShell","pandas","numpy"]

[project.scripts]
ifc2xlsx = "balajiwork.ifc2xlsx:ifc2xlsx_main"
slowprint = "balajiwork.slowprint:slow_print"

[tool.setuptools.packages.find]
where = ["."]
