[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ig_degree_betweenness"
version = "0.1.2"
description = "Smith-Pittman Community Detection Algorithm for 'igraph' Objects (2024)"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
  { name = "Benjamin Smith", email = "benyamin.smith@mail.utoronto.ca" },
  { name = "Tyler Pittman", email = "Tyler.Pittman@uhn.ca" },
  { name = "Wei Xu", email = "Wei.Xu@uhn.ca" }
]
dependencies = ["python-igraph"]
keywords = ["igraph"]
classifiers = [
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Software Development :: Libraries :: Python Modules"
]

[project.urls]
Homepage = "https://github.com/benyamindsmith/ig_degree_betweenness_py"
"Benjamin Smith ORCID" = "https://orcid.org/0009-0007-2206-0177"
"Tyler Pittman ORCID" = "https://orcid.org/0000-0002-5013-6980"
"Wei Xu ORCID" = "https://orcid.org/0000-0002-0257-8856"

[project.scripts]
ig_degree_betweenness = "ig_degree_betweenness:ig_degree_betweenness"

[tool.setuptools.packages.find]
where = ["src"]
