[project]
name = "lite-telegram"
version = "0.7.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AndKraev", email = "akrstp@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "croniter>=6.0.0",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "pydantic>=2.11.5",
    "tenacity>=9.1.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # bugbear
    "C4",  # comprehensions
    "SIM",  # simplify,
    "ASYNC"  # asyncio
]
ignore = ["E501", "ASYNC109"]