[project]
name = "mousetools"
version = "4.5.0"
authors = [{name = "Scott Caratozzolo"}]
description = "An unofficial Python wrapper for Disney's API"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.9, <4.0"
dependencies = [
    "pycryptodome>=3.22.0",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.3",
    "tzdata>=2025.2",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]

[project.urls]
repository = "https://gitlab.com/caratozzoloxyz/public/MouseTools"
documentation = "https://caratozzoloxyz.gitlab.io/public/MouseTools/"
issues = "https://gitlab.com/caratozzoloxyz/public/MouseTools/-/issues"

[tool.uv]
dev-dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.33",
    "mkdocstrings[python]>=0.25.2",
    "mypy>=1.11.2",
    "pre-commit>=3.5.0",
    "pytest-cov>=5.0.0",
    "pytest>=8.3.2",
    "ruff>=0.6.3",
    "commitizen>=4.7.0",
    "go-task-bin>=3.43.3",
    "icecream>=2.1.4",
    "pytest-mock>=3.14.0",
    "responses>=0.25.7",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
include-package-data = true

[tool.setuptools.package-data]
"mousetools" = ["resources/*"]

[tool.commitizen]
tag_format = "v$version"
legacy_tag_formats = ["$version"]
version_provider = "uv"
bump_message = "bump: version $current_version â†’ $new_version [skip ci]"

[tool.pytest.ini_options]
testpaths = ["tests"]


[tool.ruff]
target-version = "py39"
line-length = 120

[tool.ruff.lint]
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # flake8-unused-arguments
    "ARG",
    # flake8-use-pathlib
    "PTH",
    # flake8-annotations
    "ANN001", "ANN201", "ANN202", "ANN204", "ANN205", "ANN206",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # pydocstyle
    "D102", "D103", "D417",
    # pylint
    "PL",
    # pep8-naming
    "N",
    # flake8-datetimez
    "DTZ002", "DTZ003", "DTZ004", "DTZ011", "DTZ012",
    # flake8-logging-format
    "G",
    # flake8-print
    "T20",
]

ignore = [
    # LineTooLong
    "E501",
    # builtin-open
    "PTH123",
    # Magic value used in comparison
    "PLR2004",
    # Logging statement uses %
    "G002",
]

[tool.ruff.lint.per-file-ignores]
"**/tests/*" = [
    # Use of `assert` detected
    "S101",
    # Missing docstring
    "D",
    # Missing type annotation
    "ANN",
]


[tool.mypy]
python_version = "3.9"
files = ["mousetools"]
disallow_untyped_defs = "True"
disallow_any_unimported = "True"
no_implicit_optional = "True"
check_untyped_defs = "True"
warn_unused_ignores = "True"
show_error_codes = "True"
