[project]
dependencies = [
    "mcp[cli]>=1.9.4"
]
name = "chunky-mcp-utils"
version = "0.1.0"
description = "Utilities for handling large responses in chunky-mcp tools"
authors = [{ name="Ethan Winters", email="ebwinters@comcast.net" }]
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"