[project]
name = "tesorotools-python"
version = "0.0.15"
dependencies = ["psycopg2", "SQLAlchemy", "pandas", "matplotlib", "pyarrow", "python-docx", "openpyxl", "PyYAML", "babel", "eikon", "lseg-data"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/tesorotools"]
artifacts = ["src/tesorotools/assets/fonts/*.otf"]

[tool.hatch.build.targets.sdist]
packages = ["src/tesorotools"]
artifacts = ["src/tesorotools/assets/fonts/*.otf"]
