[project]
name = "aws-ssm-env"
version = "0.1.1"
description = "A lightweight utility to fetch AWS SSM parameters and inject into environment variables."
authors = [
    {name = "Angelo Antu",email = "angelo.antu@kireap.com"}
]
license = "MIT"
requires-python = ">=3.10"
packages = [{ include = "aws_ssm_env" }]
keywords = ["aws", "ssm", "environment", "parameter-store", "boto3"]

dependencies = [
    "boto3 (>=1.38.42,<2.0.0)"
]

[tool.poetry]
packages = [{include = "aws_ssm_env", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
