app:
  date_format: '%Y-%m-%d'
  enable_console_logging: true
  enable_file_logging: true
  log_backup_count: 5
  log_file_max_size: 10
  log_format: detailed
  log_level: INFO
  max_workers: 4
cli:
  elevation: true
  extract_waypoints: true
  input: ''
  min_dist: 100
  output: ''
gui:
  auto_scroll_log: true
  log_window_height: 200
  max_log_lines: 1000
  theme: light
  window_height: 600
  window_width: 800
