[project]
name = "spargear"
version = "0.2.8"
description = "Declarative and typed argument parsing built on argparse."
readme = "README.md"
license = "MIT"
requires-python = ">=3.8"
dependencies = []

[project.urls]
repository = "https://github.com/c0sogi/spargear"

[project.optional-dependencies]
dev = ["pyright>=1.1.401"]
