[project]
name = "orign"
version = "0.2.131"
description = "Adaptive Agents"
readme = "README.md"
requires-python = ">=3.11.0"
dependencies = [
    "chatmux==0.1.3",
    "loguru>=0.7.3",
    "namesgenerator>=0.3",
    "nebulous-sh==0.1.137",
    "pillow>=10.4.0",
    "pydantic>=2.11.0",
    "pyyaml>=6.0.2",
    "rclone-python>=0.1.21",
    "shortuuid>=1.0.13",
]

[tool.pyright]
reportUnknownParameterType = false
reportMissingTypeArgument = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnknownArgumentType = false
reportConstantRedefinition = false
reportUntypedFunctionDecorator = false

[dependency-groups]
dev = [
    "fastembed>=0.6.1",
    "ipykernel>=6.29.5",
    "mcp-use>=1.2.6",
    "runpod>=1.7.10",
]

[project.optional-dependencies]
gcs = [
    "google-cloud-storage",
    "google-api-core"
]
