[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "useit-client"
version = "0.0.56"
description = "."
requires-python = ">=3.11"
dependencies = [
    "opencv-python",
    "pyautogui==0.9.54",
    "streamlit>=1.38.0",
    "anthropic[bedrock,vertex]>=0.37.1",
    "jsonschema==4.22.0",
    "boto3>=1.28.57",
    "google-auth<3,>=2",
    "gradio>=5.6.0",
    "screeninfo",
    "uiautomation; sys_platform == 'win32'",
    "pywinauto; sys_platform == 'win32'",
    "textdistance",
    "matplotlib",
    "litellm",
    "requests>=2.0",
    "psutil>=5.0; sys_platform == 'win32'",
    "pywin32>=306; sys_platform == 'win32'",
    "Flask>=2.0",
    "waitress>=2.0",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.6.7",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.23.6",
    "pre-commit>=3.8.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/computer_use_ootb_internal"]
include = ["src/computer_use_ootb_internal/**/*"]  # This ensures all subpackages are included

[project.scripts]
useit-client = "computer_use_ootb_internal.app_teachmode:main"
useit-install-service = "computer_use_ootb_internal.service_manager:install_and_start"
useit-remove-service = "computer_use_ootb_internal.service_manager:stop_and_remove"

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.hatch.metadata]
allow-direct-references = true