[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "safeagent"
version = "0.0.10.2.13"
authors = [
    { name="Viktor Veselov"},
]
description = "A minimal and flexible framework for orchestrating LLM workflows."
readme = "README.md"
requires-python = ">=3.8"
license = { file="LICENSE.md" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "requests",
    "jinja2",
    "py-rbac",
    "faiss-cpu",
    "neo4j",
    "redis",
    "numpy",
    "cryptography"
]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
test = ["pytest", "pytest-mock"]