[project]
name = "havsalt-termnautica"
version = "0.1.0.dev4"
description = "Underwater game made using `charz`"
authors = [
    { name = "Havsalt", email = "77575424+Havsalt@users.noreply.github.com" }
]
dependencies = [
    "charz[all]==0.0.40",
    "pygame~=2.6",
]
readme = "README.md"
requires-python = ">= 3.13"
license = { text = "MIT" }

[project.scripts]
termnautica = "termnautica:main"

[build-system]
requires = ["maturin==1.7.0"]
build-backend = "maturin"

[tool.rye]
managed = true
dev-dependencies = []

[tool.maturin]
python-source = "python"
module-name = "termnautica"
features = ["pyo3/extension-module"]
