[project]
name = "colab-filtering"
authors = [
    {name = "Henning Schmies"},
    {email = "henning.schmies@stud.th-deg.de"},
]
version = "0.1.2"
description = "Simple package for colaborative filtering"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.0,<2.3",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python"
]
license = {file = "LICENSE.txt"}
keywords = ["big data", "colaborative filtering", "recommendation", "filtering"]

[build-system]
requires = ["hatchling>=1.22"]
build-backend = "hatchling.build"

[[tool.uv.index]]
name        = "testpypi"
url         = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit    = true

