[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tkchart"
version = "2.1.7"
authors = [
  { name = "Thisal-D" }
]

license = { file = "LICENSE" }

description = "Python library for creating live updating line charts in Tkinter."
readme = "README.md"
requires-python = ">=3.0"

classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Development Status :: 5 - Production/Stable"
]

keywords = [
  "tkchart",
  "ctkchart", 
  "linechart",
  "ctk linechart",
  "tk linechart",
  "tkinter",
  "customtkinter", 
  "line chart in tkinter",
  "line chart in customtkinter",
  "customtkinter graphic-interface",
  "tkinter graphic interface",
  "tkinter widgets",
  "customtkinter widgets",
  "python-chart",
  "tk",
  "ctk",
  "customtkinterassets",
  "tkinterassets",
  "ctk-components",
  "tk-components",
  "line-chart-for-python-tkinter",
  "line-chart-for-python-customtkinter"
]

[project.urls]
homepage = "https://github.com/Thisal-D/tkchart"
repository = "https://github.com/Thisal-D/tkchart"
issues = "https://github.com/Thisal-D/tkchart/issues"