[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tools.setuptools.packages.find]
include = ["template_nn", "template_nn.*"]

[project]
name = "template-nn"
version = "0.1.5.post1"
dependencies = [
    "torch>=2.6.0",
    "pandas>=1.0.0",
    "numpy>=1.18.0",
    "mealpy>=3.0.2",
]
authors = [
    { name = "Gabriel Choong Ge Liang", email = "gabrielchoonggeliang@gmail.com" }
]
description = "A neural network model architecture template"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = { text = "MIT" }

[project.urls]
Homepage = "https://github.com/gabrielchoong/template-nn"
Issues = "https://github.com/gabrielchoong/template-nn/issues"
