[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Fable3D"
version = "1.0.0"
description = "Prosty silnik 3D w Pythonie"
readme = "README.md"
requires-python = ">=3.6"
authors = [
  { name = "MichaÅ Lewandowski", email = "slawek.1q2w3e4r@gmail.com" }
]
license = { text = "MIT" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
dependencies = [
  "PySDL2>=0.9.17",
  "PyOpenGL>=3.1.6",
  "numpy>=1.20",
  "pyassimp>=5.2.5",
  "pillow>=11.2.1"
]