[tool.poetry]
name = "langfabric"
version = "0.1.2"
description = "Flexible LLM model initialization from YAML configuration."
authors = ["Phragman <a@staphi.com>"]
license = "MIT"
packages = [{ include = "langfabric" }]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.5"
pyyaml = "^6.0"
seyaml = "^0.1.1"
langchain = "^0.3.26"
langchain-openai = "^0.3.24"
langchain-community = "^0.3.26"
langchain-groq = "^0.3.2"

[tool.poetry.dev-dependencies]
pytest = "^8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
