[tool.poetry]
name = "lxmfy"
version = "0.7.4"
description = "LXMF bot framework for creating bots for the Reticulum Network"
authors = ["Quad4"]
readme = "README.md"
packages = [{include = "lxmfy"}]

[tool.poetry.dependencies]
python = "^3.11"
lxmf = "^0.7.1"
rns = "^0.9.6"

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.7"
interrogate = "^1.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
lxmfy = "lxmfy.cli:main"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["F401", "E501"]
exclude = [
    "tests/test_basic.py",
]