[components]
model = "epifx.det.SEIR"
time = "pypfilt.Datetime"
sampler = "pypfilt.sampler.LatinHypercube"
summary = "epifx.summary.make"

[time]
start = "2014-01-01"
until = "2014-06-30"
steps_per_unit = 5
max_forecast_ahead = 28

[files]
input_directory = "."
output_directory = "."
delete_cache_file_before_forecast = true
delete_cache_file_after_forecast = true

[prior]
R0 = { name = "uniform", args.loc = 1.4, args.scale = 0.1 }
sigma = { name = "inverse_uniform", args.inv_low = 0.2, args.inv_high = 0.3 }
gamma = { name = "inverse_uniform", args.inv_low = 0.2, args.inv_high = 0.3 }
eta = { name = "constant", args.value = 1.0 }
alpha = { name = "constant", args.value = 0.0 }
t0 = { name = "uniform", args.loc = 0.0, args.scale = 28.0 }

[filter]
particles = 20
prng_seed = 3001
history_window = 7
resample.threshold = 0.25
regularisation.enabled = true

[filter.regularisation.bounds]
R0 = { min = 1.4, max = 1.5 }
sigma = { min = 0.2, max = 0.3 }
gamma = { min = 0.2, max = 0.3 }
eta = { min = 1.0, max = 1.0 }
alpha = { min = 0, max = 0 }
t0 = { min = 0, max = 28 }

[summary]
only_forecasts = true
tables.sim_obs.observation_unit = "cases"
tables.sim_obs.common_prng_seed = true

[scenario.seir_quick]
name = "seir_quick"
model.population_size = 1_000_000

[scenario.seir_quick.observations.cases]
model = "epifx.obs.PopnCounts"
observation_period = 7
file = "weekly-cases-quick.ssv"
file_args.time_col = "time"
file_args.value_col = "cases"
parameters.bg_obs = 200
parameters.bg_var = 3000
parameters.pr_obs = 0.05
parameters.disp = 100
descriptor.format = { bg_obs = "03.0f", bg_var = "03.0f", pr_obs = "0.1f", disp = "03.0f" }
descriptor.name = { bg_obs = "bg", bg_var = "bgvar", pr_obs = "pr", disp = "disp" }
