# --- START OF FILE pyproject.toml ---

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyp6"
version = "0.1.2"
authors = [
  { name="Sanjeev Bashyal", email="sanjeev.bashyal@gmail.com" },
]
description = "A Python package for interacting with and automating workflows for Primavera P6 SQLite databases."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Database",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "pandas"
]

[project.urls]
"Homepage" = "https://github.com/SanjeevBashyal/PyP6"

# This section makes your scripts available as command-line tools
[project.scripts]
pyp6-activities = "pyp6.scripts.activities:main"
pyp6-obs        = "pyp6.scripts.obs:main"
pyp6-wbs        = "pyp6.scripts.wbs:main"
pyp6-roles      = "pyp6.scripts.roles:main"

# --- END OF FILE pyproject.toml ---