# pyproject.toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vstock-data" # Tên thư viện trên PyPI (dùng dấu gạch ngang)
version = "0.1.0" # Phiên bản đầu tiên
authors = [
  { name="Hunter Do", email="phongvu2010@gmail.com" },
]
description = "Thư viện Python tải dữ liệu chứng khoán Việt Nam từ nhiều nguồn khác nhau."
readme = "README.md"
requires-python = ">=3.11"
license = { file="LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Office/Business :: Financial :: Investment",
]

dependencies = [
    "pandas",
    "yfinance",
    "google-cloud-bigquery",
]

[project.urls]
"Homepage" = "https://github.com/phongvu2010/vStock-Data"
"Bug Tracker" = "https://github.com/phongvu2010/vStock-Data/issues"
