[project]
name = "wikipedia-mcp-server"
version = "1.0.0"
description = "A Model Context Protocol server providing tools for querying Wikipedia for LLMs."
readme = "README.md"
requires-python = ">=3.13"
authors = [
    { name = "Yang Sheng Han", email = "progamesigner@gmail.com" },
]
keywords = ["wikipedia", "mcp", "llm"]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: AsyncIO",
    "Framework :: Pydantic",
    "Framework :: Pydantic :: 2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "fastmcp>=2.9.0",
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.0",
]

[project.scripts]
wikipedia-mcp = "wikipedia_mcp:main"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.0",
]

[tool.ruff.format]
quote-style = "single"

[tool.uv]
package = true
