[project]
name = "pyright-cov"
version = "0.2.1"
description = "Run Pyright and enforce minimum type coverage"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["pyright"]

[project.scripts]
pyright-cov = "pyright_cov:main"

