[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]                # or [tool.poetry] if youâ€™re using Poetry
name = "sanalyse"
version = "0.1.0"
description = "A simple, accessible python toolkit for digital humanities scholars for basic and advanced text analysis, exploration, processing, parsing"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name="Junaid analysis", email="junaid695683@gmail.com" }
]
dependencies = [
  "annotated-types==0.7.0",
  "appnope==0.1.4",
  "asttokens==3.0.0",
  "blis==1.3.0",
  "catalogue==2.0.10",
  "certifi==2025.6.15",
  "charset-normalizer==3.4.2",
  "click==8.2.1",
  "cloudpathlib==0.21.1",
  "comm==0.2.2",
  "confection==0.1.5",
  "conllu==6.0.0",
  "contourpy==1.3.2",
  "cycler==0.12.1",
  "cymem==2.0.11",
  "debugpy==1.8.14",
  "decorator==5.2.1",
  "executing==2.2.0",
  "filelock==3.18.0",
  "fonttools==4.58.4",
  "fsspec==2025.5.1",
  "gensim==4.3.2",
  "hf-xet==1.1.5",
  "huggingface-hub==0.33.1",
  "idna==3.10",
  "ipykernel==6.29.5",
  "ipython==9.3.0",
  "ipython-pygments-lexers==1.1.1",
  "ipywidgets==8.1.7",
  "jedi==0.19.2",
  "jinja2==3.1.6",
  "joblib==1.5.1",
  "jupyter-client==8.6.3",
  "jupyter-core==5.8.1",
  "jupyterlab-widgets==3.0.15",
  "kiwisolver==1.4.8",
  "langcodes==3.5.0",
  "langdetect==1.0.9",
  "language-data==1.3.0",
  "lxml==5.4.0",
  "marisa-trie==1.2.1",
  "markdown-it-py==3.0.0",
  "markupsafe==3.0.2",
  "matplotlib==3.10.3",
  "matplotlib-inline==0.1.7",
  "mdurl==0.1.2",
  "mpmath==1.3.0",
  "murmurhash==1.0.13",
  "nest-asyncio==1.6.0",
  "networkx==3.5",
  "nltk==3.9.1",
  "numpy==2.3.1",
  "packaging==25.0",
  "pandas==2.3.0",
  "parso==0.8.4",
  "pexpect==4.9.0",
  "pillow==11.2.1",
  "platformdirs==4.3.8",
  "preshed==3.0.10",
  "prompt-toolkit==3.0.51",
  "psutil==7.0.0",
  "ptyprocess==0.7.0",
  "pure-eval==0.2.3",
  "pydantic==2.11.7",
  "pydantic-core==2.33.2",
  "pygments==2.19.2",
  "pyparsing==3.2.3",
  "python-dateutil==2.9.0.post0",
  "pytz==2025.2",
  "pyyaml==6.0.2",
  "pyzmq==27.0.0",
  "regex==2024.11.6",
  "requests==2.32.4",
  "rich==14.0.0",
  "safetensors==0.5.3",
  "scikit-learn==1.7.0",
  "scipy==1.16.0",
  "sentencepiece==0.2.0",
  "setuptools==80.9.0",
  "shellingham==1.5.4",
  "six==1.17.0",
  "smart-open==7.1.0",
  "spacy==3.8.7",
  "spacy-legacy==3.0.12",
  "spacy-loggers==1.0.5",
  "srsly==2.5.1",
  "stack-data==0.6.3",
  "sympy==1.14.0",
  "thinc==8.3.6",
  "threadpoolctl==3.6.0",
  "tokenizers==0.21.2",
  "torch==2.7.1",
  "tornado==6.5.1",
  "tqdm==4.67.1",
  "traitlets==5.14.3",
  "transformers==4.52.4",
  "typer==0.16.0",
  "typing-extensions==4.14.0",
  "typing-inspection==0.4.1",
  "tzdata==2025.2",
  "urllib3==2.5.0",
  "wasabi==1.1.3",
  "wcwidth==0.2.13",
  "weasel==0.4.1",
  "whoosh==2.7.4",
  "widgetsnbextension==4.0.14",
  "wrapt==1.17.2",
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Operating System :: OS Independent",
]