[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "araxia"
version = "0.2.0"
authors = [
  { name="Mike", email="mike@example.com" },
]
description = "A minimal neural network library built from scratch for time series forecasting and analysis."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "numpy",
]

[project.urls]
Homepage = "https://github.com/yourusername/araxia"
